name: Linter and Tests

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: lint-and-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 90

  unit-tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 60
