name: Python workflow

on:
  push:

jobs:
  ruff:
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2
      - name: Ruff check
        uses: astral-sh/ruff-action@v3

  unit-test:
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2
      - name: Install python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest .
